# Generated by Django 3.0.5 on 2020-07-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Contactno', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EnroleListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contactno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentModel')),
                ('idno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.AdminnModel')),
            ],
        ),
    ]
