# Generated by Django 3.0.5 on 2020-07-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolelistmodel',
            name='studentcontctno',
            field=models.IntegerField(null=True),
        ),
    ]
